//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using RibbonLib;
using RibbonLib.Controls;

namespace RibbonLib.Controls
{
    partial class RibbonItems
    {
        private static class Cmd
        {
            public const uint ExampleFileButton = 36;
            public const uint TabButtons = 10;
            public const uint ButtonGroup = 3;
            public const uint ExampleButtonNormal = 5;
            public const uint ExampleToggleButtonNormal = 6;
            public const uint DropDownButton = 7;
            public const uint SplitButton = 8;
            public const uint randombutton = 9;
            public const uint ButtonGroupL = 11;
            public const uint ButtL1 = 13;
            public const uint ButtL2 = 14;
            public const uint ButtonGroupLL = 12;
            public const uint ButtL3 = 15;
            public const uint ButtL4 = 16;
            public const uint ButtL5 = 17;
            public const uint MiscTab = 19;
            public const uint Misc1 = 20;
            public const uint checkb = 31;
            public const uint combob = 32;
            public const uint fidgetspinner = 33;
            public const uint colorp = 21;
            public const uint GalleriesM = 18;
            public const uint GalGroup1 = 23;
            public const uint ddgal = 22;
            public const uint galleriesstar = 35;
            public const uint GalGroup2 = 24;
            public const uint spgal = 27;
            public const uint inribgal = 29;
            public const uint CalleriesC = 28;
        }

        // ContextPopup CommandName

        public Ribbon Ribbon { get; private set; }
        public RibbonMenuGroup ExampleFileButton { get; private set; }
        public RibbonTab TabButtons { get; private set; }
        public RibbonGroup ButtonGroup { get; private set; }
        public RibbonButton ExampleButtonNormal { get; private set; }
        public RibbonToggleButton ExampleToggleButtonNormal { get; private set; }
        public RibbonDropDownButton DropDownButton { get; private set; }
        public RibbonSplitButton SplitButton { get; private set; }
        public RibbonButton randombutton { get; private set; }
        public RibbonGroup ButtonGroupL { get; private set; }
        public RibbonButton ButtL1 { get; private set; }
        public RibbonToggleButton ButtL2 { get; private set; }
        public RibbonGroup ButtonGroupLL { get; private set; }
        public RibbonDropDownButton ButtL3 { get; private set; }
        public RibbonSplitButton ButtL4 { get; private set; }
        public RibbonButton ButtL5 { get; private set; }
        public RibbonTab MiscTab { get; private set; }
        public RibbonGroup Misc1 { get; private set; }
        public RibbonCheckBox checkb { get; private set; }
        public RibbonComboBox combob { get; private set; }
        public RibbonSpinner fidgetspinner { get; private set; }
        public RibbonDropDownColorPicker colorp { get; private set; }
        public RibbonTab GalleriesM { get; private set; }
        public RibbonGroup GalGroup1 { get; private set; }
        public RibbonDropDownGallery ddgal { get; private set; }
        public RibbonButton galleriesstar { get; private set; }
        public RibbonGroup GalGroup2 { get; private set; }
        public RibbonSplitButtonGallery spgal { get; private set; }
        public RibbonInRibbonGallery inribgal { get; private set; }
        public RibbonTab CalleriesC { get; private set; }

        public RibbonItems(Ribbon ribbon)
        {
            if (ribbon == null)
                throw new ArgumentNullException(nameof(ribbon), "Parameter is null");
            this.Ribbon = ribbon;
            ExampleFileButton = new RibbonMenuGroup(ribbon, Cmd.ExampleFileButton);
            TabButtons = new RibbonTab(ribbon, Cmd.TabButtons);
            ButtonGroup = new RibbonGroup(ribbon, Cmd.ButtonGroup);
            ExampleButtonNormal = new RibbonButton(ribbon, Cmd.ExampleButtonNormal);
            ExampleToggleButtonNormal = new RibbonToggleButton(ribbon, Cmd.ExampleToggleButtonNormal);
            DropDownButton = new RibbonDropDownButton(ribbon, Cmd.DropDownButton);
            SplitButton = new RibbonSplitButton(ribbon, Cmd.SplitButton);
            randombutton = new RibbonButton(ribbon, Cmd.randombutton);
            ButtonGroupL = new RibbonGroup(ribbon, Cmd.ButtonGroupL);
            ButtL1 = new RibbonButton(ribbon, Cmd.ButtL1);
            ButtL2 = new RibbonToggleButton(ribbon, Cmd.ButtL2);
            ButtonGroupLL = new RibbonGroup(ribbon, Cmd.ButtonGroupLL);
            ButtL3 = new RibbonDropDownButton(ribbon, Cmd.ButtL3);
            ButtL4 = new RibbonSplitButton(ribbon, Cmd.ButtL4);
            ButtL5 = new RibbonButton(ribbon, Cmd.ButtL5);
            MiscTab = new RibbonTab(ribbon, Cmd.MiscTab);
            Misc1 = new RibbonGroup(ribbon, Cmd.Misc1);
            checkb = new RibbonCheckBox(ribbon, Cmd.checkb);
            combob = new RibbonComboBox(ribbon, Cmd.combob);
            fidgetspinner = new RibbonSpinner(ribbon, Cmd.fidgetspinner);
            colorp = new RibbonDropDownColorPicker(ribbon, Cmd.colorp);
            GalleriesM = new RibbonTab(ribbon, Cmd.GalleriesM);
            GalGroup1 = new RibbonGroup(ribbon, Cmd.GalGroup1);
            ddgal = new RibbonDropDownGallery(ribbon, Cmd.ddgal);
            galleriesstar = new RibbonButton(ribbon, Cmd.galleriesstar);
            GalGroup2 = new RibbonGroup(ribbon, Cmd.GalGroup2);
            spgal = new RibbonSplitButtonGallery(ribbon, Cmd.spgal);
            inribgal = new RibbonInRibbonGallery(ribbon, Cmd.inribgal);
            CalleriesC = new RibbonTab(ribbon, Cmd.CalleriesC);
        }

    }
}
